#ifndef CONFIG_H
#define CONFIG_H

#include <SDL2/SDL.h>

#define CONFIG_SDL_FLAGS (SDL_INIT_VIDEO | SDL_INIT_TIMER | SDL_INIT_EVENTS)

#define CONFIG_WINDOW_FLAGS (SDL_WINDOW_FULLSCREEN_DESKTOP | SDL_WINDOW_SHOWN)
#define CONFIG_RENDERER_FLAGS (SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC)

#define CONFIG_GL_WINDOW_FLAGS (CONFIG_WINDOW_FLAGS | SDL_WINDOW_OPENGL)

#define CONFIG_OPENAL_LIBNAME "soft_oal.dll"
#define CONFIG_LOG_FILE_PATH "Vioxity.log"

#endif